---
title: "Comedy and Mental Illness"
author: "John Ball"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
cmi <- read_csv("new version 1.csv")
```

```{r}
# cmi is a data set which administered several mental health questionnaires to
# performers in the comedy industry. The psychological questionnaires included
# in the survey are the: Mini-IPIP (Big Five Personality Measure), the Hypomanic
# Personality Scale - Short Form, CES-D (validated measure of depression), the
# O-LIFE (measure of schizotypal personality traits), and the AUDIT (a valid
# alcoholism measure). With comedic performers such as Robin Williams, Richard
# Pryor, and Sarah Silverman, it is an anecdotally accepted fact that comedy and
# mental illness often go hand-in-hand, and this data set will allow us to
# assess whether this anecdotal stereotype of the "sad clown" comedian is
# actually the case (within this sample population of 142 comedians).
```

```{r}
# To begin with, if we run a summary on the dataset, we can see that the mean
# score among comedians in the CES-D depression metric is 21.5, and the median
# is 21.0. For context, to screen positive for depression on this survey, one
# must score above 20. This means that the majority of comedians in the survey
# screened positive for depression. In contrast, in the control population, only
# 17% of individuals  screen positive for depression. 

# A large objective of this project would be to assess what other lifestyle
# questions correlate with depression and addiction among comedians. For
# instance, whether it is the stress of "making it" in the comedy industry that
# is making comedians depressed, or whether their mental illness arose much
# earlier in development.

cmi %>%
  summary()
```


